<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Riftcaster.Contracts\Riftcaster.Contracts.csproj" />
    <ProjectReference Include="..\Riftcaster.Core\Riftcaster.Core.csproj" />
  </ItemGroup>

</Project>
